### ISSUE TITLE
(Discussion) Recording Interface

### ISSUE THREAD

**Issue by josephfrazier** [onsip/rtpengine#1]
The [onsip-pcap-recording branch](https://github.com/onsip/rtpengine/tree/onsip-pcap-recording) has some [changes](https://github.com/sipwise/rtpengine/compare/rfuchs/socket-rework...onsip:onsip-pcap-recording) (in-progress) to enable media recording. This works with [OpenSIPS' rtpengine module](http://www.opensips.org/html/docs/modules/2.1.x/rtpengine) roughly as follows (feel free to correct any inaccuracies):

* Pass the "record-call=yes" flag to [rtpengine_offer](http://www.opensips.org/html/docs/modules/2.1.x/rtpengine#rtpengine.f.rtpengine_offer) and [rtpengine_answer](http://www.opensips.org/html/docs/modules/2.1.x/rtpengine#rtpengine.f.rtpengine_answer)
* As media flows, a [pcap](https://en.wikipedia.org/wiki/Pcap) file is written at `/tmp/$RANDOM_DIGITS.pcap`, where `$RANDOM_DIGITS` is exactly what it sounds like.
* Once the media terminates, the pcap file is closed.

This process currently preserves only the media packets that flowed between endpoints (note that [src/dst IP addresses are spoofed as 127.0.0.1](https://github.com/onsip/rtpengine/blob/908c76f9065e6ac495adf74e962b52af79c3339a/daemon/media_socket.c#L1226-L1227)), and doesn't include contextual information associated with the media (such as who's behind the endpoint devices).

In order to make recording more generally useful to OpenSIPS, we need a mechanism to pass along metadata about the recorded stream. Here's a couple of ideas to kick things off:

* Add another `rtpengine_offer` flag containing a string to be written to disk alongside the pcap file (`/tmp/$RANDOM_DIGITS.txt`). Then, a separate process could [watch the filesystem for changes](http://linux.die.net/man/1/inotifywait) to learn when particular calls have been completed.
* Add a way for OpenSIPS to specify the filepath, so that contextual information can be encoded into the filename.

Personally, I'm leaning towards the former solution, as it seems more flexible (note that making the `/tmp/` prefix configurable should probably be done regardless, as a separate matter), but I'm not all that familiar with the opensips/rtpengine interface, so perhaps there are better ways to do this?

**Comment by josephfrazier** [comment]
> Add another rtpengine_offer flag containing a string to be written to disk alongside the pcap file (/tmp/$RANDOM_DIGITS.txt). Then, a separate process could watch the filesystem for changes to learn when particular calls have been completed.

Here are some notes from in-person conversation between @egreenmachine, @wakamoleguy, @dbmikus, @etamme, and me about this:

* There are N pcap files per branch, and M branches per "call".
* We can configure rtpengine to only write a metadata files for each branch that successfully negotiate media.
* Usually, there is only one branch with negotiated media, but we still need to account for multiple branches somehow.
* We need a way to associate the branch's N pcap files with the one metadata file that is generated for the branch. A couple of ideas:
  * use a separate file whose path can be inferred from that of the metadata file
  * embed the pcap paths into the metadata file alongside the information from OpenSIPS

**Comment by dbmikus** [comment]
We brainstormed some options for how to do inter-process communication to signal that rtpengine finished recording a call.

First off, no matter what, we are writing the recording PCAP files to a directory. We should allow the user to specify this directory.

For the recording completion trigger, we came up with three options, detailed below.

## Write metadata to directory and watch it for updates

We can just utilize the native filesystem to indicate when a call is done recording. We would write a metadata file along with the PCAP files. The metadata file would include, at minimum, the location of all PCAP files for the call being recorded. To signal that the call is over, we have come up with some options:

1. We could write a special identifier to the metadata file.
2. We could copy or move the metadata file (and maybe all PCAP files) from a temp directory to another "watched directory".
3. We could write a separate "call completed" file.

The user can then have an external daemon monitor the directory for these files and do whatever post-processing or synchronous processing they want. This is pretty simple and lightweight from the perspective of the RTP Engine. It requires a little more work to set up a directory watcher for the post-processor. Minorly reminiscent of Plan9. :wink:


## Pass in a post-recording script to rtpengine daemon

When we run the rtpengine daemon, we can pass in a command line argument that specifies what command to run when a call is finished recording. All of the PCAP file locations can be passed to this command/executable. This is very easy from the user perspective. One downside is that the rtpengine will be doing a fair amount of fork-exec. Not sure of the performance ramifications.

## Write to a POSIX message queue

We can use [POSIX message queues](http://linux.die.net/man/7/mq_overview) or [System V message queues](https://en.wikipedia.org/wiki/Message_queue#Implementation_in_UNIX). The user (or rtpengine) will have to mount a message queue filesystem and rtpengine can set up the queue. Another daemon can then poll the queue for messages.

**Comment by josephfrazier** [comment]
> Write metadata to directory and watch it for updates

Given that we're already writing the PCAP files to a filesystem, I think that also writing the metadata is the least opinionated solution, and imposes the fewest extra requirements on rtpengine.

Note that rtpengine users may not necessarily be interested in processing recording files as they are generated, and therefore may have no need for the other two solutions (post-recording script or POSIX queue). Simply writing all the information to disk allows these users to process the recordings in batches, while preserving the flexibility to use something like [`inotifywait`](http://linux.die.net/man/1/inotifywait) to learn about the files as they are generated.

> To signal that the call is over, we have come up with some options:

> 1. We could write a special identifier to the metadata file.
2. We could copy or move the metadata file (and maybe all PCAP files) from a temp directory to another "watched directory".
3. We could write a separate "call completed" file

At a first glance, it seems like writing a separate "call completed" file would work the best for both groups of users mentioned above: those that process recordings in batches, and those that process them as they are generated. The batch users can simply look for the special file, while the "streaming" users can wait for the special files to be closed (`inotifywait --event close_write`). Keeping everything the same directory also seems a little simpler to me than moving files between directories.

**Comment by rfuchs** [comment]
I've been invited here to give my thoughts on this topic by @etamme as I'm the maintainer of rtpengine.

My personal preference would be to do it through the filesystem for simplicity's sake, either through inotify or by flagging completed files in some way. The inotify mechanism should always work, and for flagging completed files, I'd prefer a solid filesystem-atomic operation. Writing files isn't atomic, but `rename` is (either actually renaming files, or moving them to another directly as long as it's on the same filesystem) and so is creating files, so one of these should work.

That being said, I don't really have a strong opinion on this as it's not my project and I think the notification mechanism is a minor detail that can always be extended with other optional mechanisms in the future. If a message queue would make things easier for you, then by all means go with that.

Since the control protocol between the SIP proxy and rtpengine has been mentioned, let me just comment that it's very flexible and that it can be extended almost arbitrarily (akin to JSON) in both directions (passing data from the SIP proxy to rtpengine as well as back). The only thing that is not possible at the moment is an asynchronous callback (i.e. event notification) from rtpengine back to the SIP proxy.

**Comment by dbmikus** [comment]
Finished up by 00aa4a973. We use the filesystem for notifications, writing metadata files to `/tmp/rtpengine/` as the call proceeds, and then we move the metadata file to `/var/spool/rtpengine/metadata` when the call is finished. We are going to make the spool directory configurable (see #6), but we will still use `/var/spool/rtpengine` as a default if nothing else is specified.

Documentation on the output file format can be found in `daemon/fs.h`, but here it is for ease of viewing:


Metadata file format is (with trailing newline):

> /path/to/rec-pcap01.pcap
> /path/to/rec-pcap02.pcap
> ...
> /path/to/rec-pcap0n.pcap
>
> start timestamp (YYYY-MM-DDThh:mm:ss)
> end timestamp   (YYYY-MM-DDThh:mm:ss)
>
> metadata
