### ISSUE TITLE
Escape call-id when writing files

### ISSUE THREAD

**Issue by egreenmachine** [onsip/rtpengine#16]
One of our sysadmins is reporting that the call-ids that we are using for filenames could be an issue with Unix. Just to be safe we should escape the call-id when writing it to disk.

Examples
```
/var/spool/rtpengine/pcaps/dc9c83a49d034be3c00d33b85643d5fb@0:0:0:0:0:0:0:0-822ea6ce2188c2c9.pcap
/var/spool/rtpengine/pcaps/4e482495987113f6642665d477a21021@0:0:0:0:0:0:0:0-e76c60ae364d026d.pcap
/var/spool/rtpengine/pcaps/7093fb165de801101300f6c36a9f6f4b@0:0:0:0:0:0:0:0-66fe6d04abf4d092.pcap
/var/spool/rtpengine/pcaps/528399b339c32b6923257b0e9c0a623b@0:0:0:0:0:0:0:0-ca6fc0dba9d2ea4f.pcap
```
The `@0:0:0:0:0:0:0:0` could be an issue. The call-id was generated with Jitsi UA.

**Comment by dbmikus** [comment]
I'm going to replace "@" and ":" with hyphens.

**Comment by egreenmachine** [comment]
It might be better to just URI encode. That way you could still easily match it to a call-id without doing any fuzzy logic or substitutions.

**Comment by josephfrazier** [comment]
Yeah, the reason the Call-ID is in the filename in the first place is to make it easier to associate the file with the call. Any filename transformation should be as minimal/standard as possible, IMO. For reference, here are the relevant parts of the [SIP grammar](https://tools.ietf.org/html/rfc3261#page-228):

```
      callid      =  word [ "@" word ]

      word        =  1*(alphanum / "-" / "." / "!" / "%" / "*" /
                     "_" / "+" / "`" / "'" / "~" /
                     "(" / ")" / "<" / ">" /
                     ":" / "\" / DQUOTE /
                     "/" / "[" / "]" / "?" /
                     "{" / "}" )
```

As far as I can tell, the "/" character is the only one that is allowed in the Call-ID, but prohibited from Unix filenames. However, it might be nice to avoid [others](https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words).

**Comment by dbmikus** [comment]
I did a good amount of reading on what to avoid. @egreenmachine's solution seems like the simplest and best idea. It's done here: e87f392d09482483b7df5b543977b58f4fb7c137
