### ISSUE TITLE
Update description of metadata file to include both offer and answer SDP

### ISSUE THREAD

**Issue by dbmikus** [onsip/rtpengine#17]
In the README and in recording.h, we describe the template for the metadata file. See here for the recording.h comments: https://github.com/onsip/rtpengine/blob/call-recording/daemon/recording.h#L45-L76

It says that it records the answer SDP only, but we have since changed it to write down both the offer and answer SDP. Update this documentation.

**Comment by egreenmachine** [comment]
Resolved with 505700346b835455f5b1a974d413454ac0fc7444
