### ISSUE TITLE
Write meta-data if call-recording is set to yes or metadata passed in

### ISSUE THREAD

**Issue by dbmikus** [onsip/rtpengine#3]
Right now, we only write out the metadata file if metadata is present. We should write out the metadata file if either (or both) of the following is true:

1. The call is being recorded
2. We passed metadata into the RTP Engine

**Comment by egreenmachine** [comment]
584285c0d845eb577a120f873d1446c3d385e9c0 is only writing the meta-data if the call-recording flag is set to true. We think that this should be ok, and if there is a use case for writing the meta-data even if the call is not recorded we can modify this in the future.
