### ISSUE TITLE
Handle meta-data being sent to rtpengine multiple times per call

### ISSUE THREAD

**Issue by dbmikus** [onsip/rtpengine#5]
In the RTP Engine, we can pass metadata to the RTP Engine through commands. Currently, a call only has one metadata instance and subsequent commands that target the call will overwrite the metadata. We must make sure to free metadata that is overwritten before assigning the new metadata.

Metadata is associated with the call. So, for every command, we want to overwrite the metadata from the old command if metadata was actually passed in.

**Comment by egreenmachine** [comment]
I am overwriting the metadata with correctly freeing the previous metadata. 425ace45f7dcb7055ce089edcce61ba14a686d2e
