### ISSUE TITLE
Allow user to configure directory for pcap and metadata files via command line

### ISSUE THREAD

**Issue by dbmikus** [onsip/rtpengine#6]
The directory for storing PCAP files and the directory for metadata files are both hardcoded right now. They reside within `/var/spool/rtpengine/{recordings | metadata}`, respectively. This path should be configurable.

I vote that the user just sets the rtpengine spool directory and "recordings" and "metadata" will be created if not present and they will be used. Then if the user actually wants to make them point somewhere else, they can use symbolic links.

I'm not overly attached to that plan, but if anyone wants to do it a different way, I would like to know why.

**Comment by josephfrazier** [comment]
> I vote that the user just sets the rtpengine spool directory and "recordings" and "metadata" will be created if not present and they will be used. Then if the user actually wants to make them point somewhere else, they can use symbolic links.

I agree with this. Simply letting the user override `/var/spool/rtpengine` seems sufficient for now.

A somewhat related matter that comes to mind is whether rtpengine should create the specified directory if it is missing. If I recall correctly, our original attitude on this was that the user should be responsible for creating the directory. However, it seems reasonable to me that if the default  is `/var/spool/rtpengine`, then rtpengine should attempt to create it on startup (and probably should do the same for explicitly-specified directories).

**Comment by dbmikus** [comment]
I think that it does make sense for the RTP Engine to create the default directory automatically if that is the one being used.

If the user is specifying an alternative directory, they should have to create it.

@etamme: I know you previously said that the `/var/spool/rtpengine` should have to be created before running the RTP Engine, and I agreed then. Do you still think that should be the case, even if we have the option to set an alternative directory?

Also, should the whole spool thing be an option for the RTP Engine? Like, a preprocessor flag or something during compilation, saying you want all this recording stuff?

**Comment by josephfrazier** [comment]
Yes, the directory-creation behavior I had in mind was:

* default directory -> try to create if needed, then log a warning if it's not present (warning-only since the user may not be interested in recording)
* specified directory -> try to create if needed, then crash if it's not present (crash since the user is clearly interested in recording)

> Also, should the whole spool thing be an option for the RTP Engine? Like, a preprocessor flag or something during compilation, saying you want all this recording stuff?

Would these flags be only for specifying the default directory location, or also for specifying whether recording is at all possible? I'm not sure I understand the need for either, given that the default (that is, non-recording) behavior of rtpengine *shouldn't* change from the addition of the recording code. Nevertheless, I could see why having a preprocessor flag to remove all recording code could help it get upstream faster (for example, if there were concerns about stability/performance/etc)

**Comment by dbmikus** [comment]
Pushed 19959ab2ea09d8b6b769aa21dc2dcea85c360342. Command line option is "--recording-dir". I think we should go over the name as a group, because it is part of the public interface. "--recording-dir" is a little weird, IMO, because if we have:

```
--recording-dir=/var/spool/foobar
```

then there will also be paths

```
--recording-dir=/var/spool/foobar/recordings
--recording-dir=/var/spool/foobar/metadata
```

We use the `--recording-dir` option to refer to the parent directory, but inside there is another recordings directory. `--spool-dir` is generic (and might be useful for future things), but right now it doesn't indicate what the directory or option is **actually** for. I'm not sure what the right name is.

Anyways, the interface for specifying a recording spool directory behaves in the following way:

- The RTP Engine will not try to create the spool directory. It will only check for it. I went with this just because that's how it previously worked.
- If you don't pass in a specific directory, it defaults to `/var/spool/rtpengine/`. If that directory doesn't exist, the program logs a warning, but continues anyways. It will not record any PCAP files. This is for users that don't want to record anything.
- If you **do** pass in a directory but the directory does not exist, the rtpengine will exit and tell the user to create the directory before running the rtpengine.

- - -

After we finalize the name of the recording/spool path option, we need to also update [README.md](https://github.com/onsip/rtpengine/blob/onsip-pcap-recording/README.md).

**Comment by josephfrazier** [comment]
>  if we have:

> ```
--recording-dir=/var/spool/foobar
```

> then there will also be paths

> ```
--recording-dir=/var/spool/foobar/recordings
--recording-dir=/var/spool/foobar/metadata
```

What if we used "pcaps" as the name of the directory containing pcap files (so, `/var/spool/foobar/pcaps`)? That seems a little clearer to me.

**Comment by dbmikus** [comment]
I like that, @josephfrazier.

**Comment by dbmikus** [comment]
Name updated in 3aab26194b24545a7378bec7b9b3f4d2b96a4335.

**Comment by dbmikus** [comment]
README updated in 000483da6e003f9a904f97aca78058227f647655 and 70e3dc3955014f2d6aeab607752dadfee2d892b4.
