### ISSUE TITLE
Rebase onsip-pcap-recording onto sipwise/master

### ISSUE THREAD

**Issue by dbmikus** [onsip/rtpengine#9]
sipwise/rtpengine had a manual merge commit: https://github.com/sipwise/rtpengine/commit/6d3865b9710402509acb0e688095ba1e2e53ac1d

I backed up my branches locally and set about rebasing. The rebase finished, but there are errors. Here are some of them:

1. [x] Lingering `recording_fd` references must be removed.
2. [x] Console printing of statements while rtpengine is starting up need to be fixed so they actually print.
3. [x] `call->monologues` changed data types. We need to make the recording code work with the new `GQueue` type.

There are probably more broken things. I'm not going to push this yet because I'm trying to make the changes in the commit history. I don't want it to get any harder to make a pull request, so I'm trying to keep it sort of neat.

**Comment by josephfrazier** [comment]
I also gave this a shot.

5e788c6 is where the onsip-pcap-recording branch originally diverged from rfuchs/socket-rework, so I moved our changes after that commit to the master branch using:

    git rebase -i --autosquash --onto master 5e788c6 onsip-pcap-recording


It probably doesn't address any of the issues you mentioned in the checkboxes above, but you can see the results here: https://github.com/sipwise/rtpengine/compare/master...onsip:rebase-i-autosquash-onto-master-5e788c6b7bc2559a048096394c95a3ada0f898bb-onsip-pcap-recording

Here's `git diff 5e788c6...onsip-pcap-recording` for comparison: https://github.com/sipwise/rtpengine/compare/5e788c6b7bc2559a048096394c95a3ada0f898bb...onsip:onsip-pcap-recording

**Comment by dbmikus** [comment]
Done. It works. I'm going to make a pull request against ourselves so everyone can see the final set of commits and comment on the log messages and have an easy glimpse at all the changed code for any late review.

**Comment by dbmikus** [comment]
Opening this back up because I lost some README code changes, and I forgot to do an overall comparison to master and to pre-rebase code.

**Comment by dbmikus** [comment]
Fixed README changes. More work is being done on the branch now, so not ready for a merge yet, but I'm going to close this issue.
